// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRx391zLEncIbKlbBl-U_fgLNccOlKQaQ',
    appId: '1:18065069966:web:6ece42651e9cbb011c76df',
    messagingSenderId: '18065069966',
    projectId: 'smart-pre-recycling-e3287',
    authDomain: 'smart-pre-recycling-e3287.firebaseapp.com',
    storageBucket: 'smart-pre-recycling-e3287.firebasestorage.app',
    measurementId: 'G-PXP6QM50QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvikAZ7Aage939y7yASGnFSGjrBq4Y_pU',
    appId: '1:18065069966:android:d334b8ab6786bb2d1c76df',
    messagingSenderId: '18065069966',
    projectId: 'smart-pre-recycling-e3287',
    storageBucket: 'smart-pre-recycling-e3287.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoi0uHF4X-d6wNG2_la013Z3P_3gq6GBk',
    appId: '1:18065069966:ios:68d6ab351b0e32d91c76df',
    messagingSenderId: '18065069966',
    projectId: 'smart-pre-recycling-e3287',
    storageBucket: 'smart-pre-recycling-e3287.firebasestorage.app',
    iosClientId: '18065069966-to2bhcv45tb6cj0ovbv0fhractbof46h.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPreRecycling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoi0uHF4X-d6wNG2_la013Z3P_3gq6GBk',
    appId: '1:18065069966:ios:68d6ab351b0e32d91c76df',
    messagingSenderId: '18065069966',
    projectId: 'smart-pre-recycling-e3287',
    storageBucket: 'smart-pre-recycling-e3287.firebasestorage.app',
    iosClientId: '18065069966-to2bhcv45tb6cj0ovbv0fhractbof46h.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPreRecycling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRx391zLEncIbKlbBl-U_fgLNccOlKQaQ',
    appId: '1:18065069966:web:8a3e9da6ffc986fa1c76df',
    messagingSenderId: '18065069966',
    projectId: 'smart-pre-recycling-e3287',
    authDomain: 'smart-pre-recycling-e3287.firebaseapp.com',
    storageBucket: 'smart-pre-recycling-e3287.firebasestorage.app',
    measurementId: 'G-F14HMKXNHZ',
  );
}
